### ISSUE TITLE
HTML source code display script incorrectly includes containing div, omits comments, and omits HTML inside script templates.

### ISSUE THREAD

**Issue by mcking65** [w3c/aria-practices#294]
[examples/js/examples.js](https://github.com/w3c/aria-practices/blob/master/examples/js/examples.js) has the following three bugs.

1. The container div is included in the output. If an example is wrapped in `<div id="ex1">`, and you call `sourceCode.add('sc1', 'ex1')`, the `'ex1'` div is part of the output. It should not be. We only want the stuff inside of the div.
2. HTML comments `<!-- ... -->` are left out of the output. They should be included.
3. HTMLL markup inside of a `<script>` element is left out. It should be included. For instance, this happens with the script tag in the [alert example](http://w3c.github.io/aria-practices/examples/alert/index.html). The `<p>` tags inside the `<script>` tag is not included in the example.js output.

**Comment by jongund** [comment]
Looks like this problem has been fixed by someone else

**Comment by mcking65** [comment]
@jongund,

Looking at the [history for examples.js](https://github.com/w3c/aria-practices/commits/master/examples/js/examples.js), I don't see a commit with fixes for this issue.

Looking at example pages, I still see the problems listed in the issue description.

**Comment by jongund** [comment]
These issues with code generation should be resolved now

**Comment by mcking65** [comment]
Today's commit resolved this issue. Thank you @jongund.
